<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV5kbc4d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV5kbc4d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV5kbc4d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV5kbc4d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV5kbc4d\App_KernelDevDebugContainer([
    'container.build_hash' => 'V5kbc4d',
    'container.build_id' => 'b86f12c3',
    'container.build_time' => 1656359594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV5kbc4d');
